Lions_Heart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [

    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^', include('lions_heart_products.urls')),
    url(r'^', include('lions_heart_blog.urls')),
    url(r'^', include('lions_heart_cart.urls')),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(url(r'^', include('lions_heart_products.urls')))
urlpatterns += i18n_patterns(url(r'^', include('lions_heart_blog.urls')))
urlpatterns += i18n_patterns(url(r'^', include('lions_heart_cart.urls')))

if settings.DEBUG:
        import debug_toolbar
        urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls))] + urlpatterns

lions_heart_app/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.db import transaction


class Category(MPTTModel):

    class Meta(object):
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    title = models.CharField(max_length=256, verbose_name='наименование')

    parent = TreeForeignKey('self', null=True, blank=True, related_name='children',
                            db_index=True, on_delete=models.CASCADE, verbose_name='родительская категория')

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        return "{}".format(self.title)


class Collection(models.Model):

    class Meta(object):
        verbose_name = "Коллекция"
        verbose_name_plural = "Коллекции"

    title = models.CharField(max_length=256, verbose_name='наименование')

    def __str__(self):
        return "{}".format(self.title)


class Item(models.Model):

    class Meta(object):
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ['-created']

    TYPE_CHOICES = (('Мужская', 'Мужская'),
                   ('Женская', 'Женская'))

    created = models.DateTimeField(auto_now_add=True)

    title = models.CharField(max_length=256, verbose_name='наименование')

    description = models.TextField(blank=True, null=True, verbose_name='описание')

    price = models.FloatField(verbose_name='цена')

    slug = models.SlugField(blank=True, null=True)

    type = models.CharField(choices=TYPE_CHOICES, max_length=7, default='Женская', verbose_name='тип коллекции')

    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')

    collection = models.ForeignKey(Collection, null=True, on_delete=models.CASCADE, verbose_name='коллекция')

    recommended_items = models.ManyToManyField('self', blank=True, verbose_name='рекомендованные товары')

    def __str__(self):
        return "{}-{}".format(self.category, self.title)


class Image(models.Model):

    class Meta(object):
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения"

    image = models.ImageField(upload_to='media', verbose_name='изображение')

    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name='товар')

    main_image = models.BooleanField(default=False, verbose_name='титульное изображение')

    '''@transaction.atomic
    def save(self, *args, **kwargs):
        if self.main_image:
            Image.objects.filter(
                main_image=True).update(main_image=False)
        super(Image, self).save(*args, **kwargs)'''

    def __str__(self):
        return "{}-{}".format(self.item, self.image)


class Specs(models.Model):

    class Meta(object):
        verbose_name = "Характеристика товара"
        verbose_name_plural = "Характекристики товара"

    specs = models.TextField(verbose_name='характекристики товара')

    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name='товар')

    def __str__(self):
        return "{}".format(self.item)

lions_heart_app/templates/lions_heart_app/catalogue.html
{% extends 'lions_heart_app/index.html' %}

{% block content %}

     {% for item in object_list %}

       <p><a href="{% url 'item' item.pk  %}">{{ item.title }}</a></p>

         {% for image in item.image_set.all %}

             {% if image.main_image %}

         <p><img src={{ image.image.url }} /></p>

             {% endif %}

         {% endfor %}

         <p>Цена: {{ item.price }}</p>
       <p>Коллекция: {{ item.collection }}</p>
       <p>Категория: {{ item.category }}</p>

         <p><a class="btn btn-primary" href="{% url 'add_to_cart' item.pk %}" role="button">Add to cart</a></p>


         <p>Рекомендованные: {% for product in item.recommended_items.all %}
                            {{ product.title }}
                            {% endfor %}
       </p>

        <hr>

    {% endfor %}

{% endblock content %}

lions_heart_app/templates/lions_heart_app/item_detail.html
{% extends 'lions_heart_app/index.html' %}

{% block content %}



       <p>{{ item.title }}</p>

    {% for image in item.image_set.all %}
        <p><img src={{ image.image.url }} /></p>
    {% endfor %}

        <p>Цена: {{ item.price }}</p>
       <p>Коллекция: {{ item.collection }}</p>
       <p>Категория: {{ item.category }}</p>
       <p>Рекомендованные: {% for product in item.recommended_items.all %}
                            {{ product.title }}
                            {% endfor %}
       </p>

    <p><a class="btn btn-primary" href="{% url 'add_to_cart' item.pk %}" role="button">Add to cart</a></p>


{% endblock content %}