Lions_Heart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [

    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^', include('lions_heart_products.urls')),
    url(r'^', include('lions_heart_blog.urls')),
    url(r'^', include('lions_heart_cart.urls')),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(url(r'^', include('lions_heart_products.urls')))
urlpatterns += i18n_patterns(url(r'^', include('lions_heart_blog.urls')))
urlpatterns += i18n_patterns(url(r'^', include('lions_heart_cart.urls')))

if settings.DEBUG:
        import debug_toolbar
        urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls))] + urlpatterns

lions_heart_products/urls.py
from django.conf.urls import url
from .views import HomeView, ItemDetailView, CollectionListView, CategoryCollectionListView, \
    SalesListView, CollectionSalesListView, update_size


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^catalogue/collections/(?P<collection_id>\d+)/$', CollectionListView.as_view(), name='collection'),
    url(r'^catalogue/collections/(?P<collection_id>\d+)/categories/(?P<category_id>\d+)/$',
        CategoryCollectionListView.as_view(), name='collection_category'),

    url(r'^catalogue/sales/$', SalesListView.as_view(), name='sales'),
    url(r'^catalogue/sales/collection/(?P<collection_id>\d+)/$',
        CollectionSalesListView.as_view(), name='sales_collection'),

    url(r'^catalogue/items/(?P<pk>\d+)/$', ItemDetailView.as_view(), name='item'),
    url(r'^update_size/(?P<item_id>\d+)/$', update_size, name='update_size'),
                ]

lions_heart_blog/models.py
from django.db import models
from lions_heart_products.models import CommonInfo
from django.utils.translation import ugettext_lazy as _


class Post(CommonInfo):

    class Meta(CommonInfo.Meta):
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")

    title = models.CharField(max_length=256, verbose_name=_('name'))
    body_text = models.TextField(blank=True, null=True, verbose_name=_('text'))
    main_image = models.ImageField(blank=True, null=True, upload_to='blog/pictures',
                                   verbose_name=_('main image'))

    def __str__(self):
        return "{}".format(self.title)


class Comment(CommonInfo):

    class Meta(CommonInfo.Meta):
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

    author = models.CharField(max_length=256, blank=True, null=True, verbose_name=_('author'))
    comment = models.TextField(blank=True, null=True, verbose_name=_('comment'))
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name=_('post'))

    def __str__(self):
        return "{}-{}".format(self.post, self.created)


class Image(models.Model):

    class Meta(object):
        verbose_name = _("Image")
        verbose_name_plural = _("Images")

    image = models.ImageField(upload_to='blog/pictures', verbose_name=_('image'))
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name=_('post'))

    def __str__(self):
        return "{}-{}".format(self.image, self.post)


class CompanyInformation(models.Model):

    class Meta(object):
        verbose_name = _("Company")
        verbose_name_plural = _("Company")

    about = models.TextField(verbose_name=_('about'))
    about_title_image = models.ImageField(blank=True,
                                          null=True,
                                          upload_to='company/pictures',
                                          verbose_name=_('about_image'))
    banner_title = models.CharField(max_length=256, blank=True, null=True)


class Phone(models.Model):
    phone = models.CharField(max_length=256)
    company = models.ForeignKey(CompanyInformation, on_delete=models.CASCADE)


class Email(models.Model):
    mail = models.EmailField()
    company = models.ForeignKey(CompanyInformation, on_delete=models.CASCADE)


class Address(models.Model):
    address = models.CharField(max_length=256)
    company = models.ForeignKey(CompanyInformation, on_delete=models.CASCADE)


class CompanyImage(models.Model):

    class Meta(object):
        verbose_name = _("Diploma")
        verbose_name_plural = _("Diplomas")

    image = models.ImageField(upload_to='company/pictures', verbose_name=_('image'))
    company = models.ForeignKey(CompanyInformation, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.image)


class Banners(models.Model):

    class Meta(object):
        verbose_name = _("Banner")
        verbose_name_plural = _("Banners")

    image = models.ImageField(upload_to='company/pictures', verbose_name='banner')
    company = models.ForeignKey(CompanyInformation, on_delete=models.CASCADE)
    is_revived = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.image)


class Reviews(CommonInfo):

    class Meta(CommonInfo.Meta):
        verbose_name = _("Review")
        verbose_name_plural = _("Reviews")

    author = models.CharField(max_length=35, verbose_name=_('name'))
    review = models.TextField(max_length=1332, verbose_name=_('review'))

    def __str__(self):
        return "{}-{}".format(self.created, self.author)

lions_heart_products/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import ugettext_lazy as _
from positions import PositionField


class CommonInfo(models.Model):

    class Meta:
        abstract = True
        ordering = ['-created']

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Category(MPTTModel):

    class Meta(object):
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    slug = models.SlugField(blank=True, null=True)
    title = models.CharField(max_length=256, verbose_name=_('title'))
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children',
                            db_index=True, on_delete=models.CASCADE, verbose_name=_('parent сategory'))
    lions_heart_present = models.BooleanField(default=True)
    revived_present = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        return "{}".format(self.title)


class Collection(models.Model):

    class Meta(object):
        verbose_name = _("Сollection")
        verbose_name_plural = _("Сollections")

    slug = models.SlugField(blank=True, null=True)
    title = models.CharField(max_length=256, verbose_name=_('name'))
    logo_image = models.ImageField(upload_to='collection/logos', verbose_name=_('logo'),
                                   blank=True, null=True)
    description = models.TextField(verbose_name=_('description'), blank=True, null=True)

    def __str__(self):
        return "{}".format(self.title)


class Item(CommonInfo):

    class Meta(CommonInfo.Meta):
        verbose_name = _("Item")
        verbose_name_plural = _("Items")

    TYPE_CHOICES = ((_('Men'), _('Men')),
                    (_('Women'), _('Women')))

    title = models.CharField(max_length=256, verbose_name=_('name'))
    title_image = models.ImageField(upload_to='catalog/products', verbose_name=_('title image'))
    description = models.TextField(blank=True, null=True, verbose_name=_('description'))
    slug = models.SlugField(blank=True, null=True)
    type = models.CharField(choices=TYPE_CHOICES, max_length=7, default=_('Women'), verbose_name=_('type'))
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=_('сategory'))
    collection = models.ForeignKey(Collection, null=True, on_delete=models.CASCADE, verbose_name=_('сollection'))
    recommended_items = models.ManyToManyField('self', blank=True, verbose_name=_('recommended'))
    sales = models.IntegerField(verbose_name=_('sales, %'), blank=True, null=True)
    best_seller = models.BooleanField(default=False)
    is_not_leather_chain = models.BooleanField(default=True)
    position = PositionField()
    is_available = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.sales:
            for item in self.attributes_set.all():
                item.sales_price = item.price - item.price * self.sales / 100
                item.save()
        else:
            for item in self.attributes_set.all():
                item.sales_price = None
                item.save()
        super().save(*args, **kwargs)

    def get_first_attribute(self):
        return Attributes.objects.filter(item=self).first()

    def __str__(self):
        return "{}-{}-{}-{}".format(self.collection, self.category, self.title, self.position)


class Image(models.Model):

    class Meta(object):
        verbose_name = _("Image")
        verbose_name_plural = _("Images")

    image = models.ImageField(upload_to='catalog/products', verbose_name=_('image'))
    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name=_('item'))

    def __str__(self):
        return "{}-{}".format(self.item, self.image)


class Specs(models.Model):

    class Meta(object):
        verbose_name = _("Specs")
        verbose_name_plural = _("Specs")

    specs = models.TextField(blank=True, null=True, verbose_name=_('other specs'))
    item = models.OneToOneField(Item, on_delete=models.CASCADE)


class Attributes(models.Model):

    class Meta(object):
        verbose_name = _("Attribute")
        verbose_name_plural = _("Attributes")

    size = models.FloatField(blank=True, null=True)
    weight = models.FloatField(blank=True, null=True, verbose_name='weight, gr')
    price = models.DecimalField(max_digits=11, decimal_places=2, verbose_name='price')
    sales_price = models.DecimalField(max_digits=11, decimal_places=2,
                                      blank=True, null=True, verbose_name='sales price')
    diameter = models.FloatField(blank=True, null=True, verbose_name='diameter, mm')
    length = models.FloatField(blank=True, null=True, verbose_name='length, cm')
    width = models.FloatField(blank=True, null=True, verbose_name='width, mm')
    height = models.FloatField(blank=True, null=True, verbose_name='height, mm')
    item = models.ForeignKey(Item, on_delete=models.CASCADE)


class CurrencyRate(CommonInfo):

    class Meta(CommonInfo.Meta):
        verbose_name = _("Rate")
        verbose_name_plural = _("Rates")

    rate = models.FloatField()

    def __str__(self):
        return "{}-{}".format(self.created, self.rate)

lions_heart_products/forms.py
from django import forms
from .models import Attributes


class AttributesForm(forms.Form):

    def __init__(self, pk, *args, **kwargs):
        super(AttributesForm, self).__init__(*args, **kwargs)
        self.fields['size'] = forms.ChoiceField(
            choices=[(i.size, str(i.size)) for i in Attributes.objects.filter(item=pk)])

lions_heart_products/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse
from django.views.generic import TemplateView, ListView, DetailView
from .models import Item, Category, Collection, Attributes, Specs
from .forms import AttributesForm
from django.http import JsonResponse
from lions_heart_products.templatetags.mytemplatetags import get_rate
from decimal import Decimal


class HomeView(TemplateView):
    template_name = 'lions_heart_products/index.html'


class CollectionListView(ListView):
    model = Item
    template_name = 'lions_heart_products/collection.html'
    paginate_by = 7

    def get_queryset(self):
        queryset = super(CollectionListView, self).get_queryset()
        collection_id = self.kwargs['collection_id']
        if collection_id == '2':
            return queryset.filter(collection=self.kwargs['collection_id']).order_by('created')
        return queryset.filter(collection=self.kwargs['collection_id']).order_by('position')

    def get_context_data(self, **kwargs):
        context = super(CollectionListView, self).get_context_data(**kwargs)
        context['collects'] = get_object_or_404(Collection, id=self.kwargs['collection_id'])
        context['paginate_by'] = int(self.request.GET.get('paginate_by', self.paginate_by))
        return context

    def get_paginate_by(self, queryset):
        return int(self.request.GET.get('paginate_by', self.paginate_by))


class CategoryCollectionListView(CollectionListView):

    def get_queryset(self):
        queryset = super(CategoryCollectionListView, self).get_queryset()
        category_id = self.kwargs['category_id']
        if category_id == '7':
            return queryset.filter(collection=self.kwargs['collection_id'],
                            category=self.kwargs['category_id']).order_by('-is_not_leather_chain', 'position')
        return queryset.filter(collection=self.kwargs['collection_id'], category=self.kwargs['category_id'])

    def get_context_data(self, **kwargs):
        context = super(CategoryCollectionListView, self).get_context_data(**kwargs)
        context['categs'] = get_object_or_404(Category, id=self.kwargs['category_id'])
        return context


class SalesListView(ListView):
    model = Item
    template_name = 'lions_heart_products/sales.html'
    paginate_by = 8
    ordering = ['position']

    def get_queryset(self):
        queryset = super(SalesListView, self).get_queryset()
        return queryset.filter(sales__isnull=False)


class CollectionSalesListView(SalesListView):
    paginate_by = 7

    def get_queryset(self):
        queryset = super(CollectionSalesListView, self).get_queryset()
        return queryset.filter(sales__isnull=False, collection=self.kwargs['collection_id'])

    def get_context_data(self, **kwargs):
        context = super(CollectionSalesListView, self).get_context_data(**kwargs)
        context['selected'] = get_object_or_404(Collection, id=self.kwargs['collection_id'])
        return context


class ItemDetailView(DetailView):
    model = Item
    template_name = 'lions_heart_products/item_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ItemDetailView, self).get_context_data(**kwargs)
        context['form'] = AttributesForm(pk=self.kwargs.get('pk'))
        return context


def update_size(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    response_data = {}
    rate = get_rate()
    if request.method == 'POST':
        chosen_size = request.POST['size']
        attributes = Attributes.objects.filter(size=chosen_size, item=item).first()
        response_data['price'] = Decimal(round(float(attributes.price) * rate)).quantize(Decimal('.00'))
        if attributes.sales_price:
            response_data['sales_price'] = Decimal(round(float(attributes.sales_price) * rate)).quantize(Decimal('.00'))
        response_data['weight'] = str(attributes.weight)
        response_data['diameter'] = str(attributes.diameter)
        response_data['width'] = str(attributes.width)
        response_data['height'] = str(attributes.height)
        response_data['length'] = str(attributes.length)
        response_data['size_id'] = attributes.id
    return JsonResponse(response_data)

lions_heart_products/templates/lions_heart_products/collection.html
{% extends 'lions_heart_products/index.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load mytemplatetags %}
{% load thumbnail %}
{% load static from staticfiles %}

{% block content %}


    <!--BREADCUMBS-->
    <div class="breadcumbs">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav class="nav">
                        <ul class="nav__list">
                            <li class="nav__item nav__item_inline"><a class="breadcumbs__link nav__link nav__link_dark"
                                                                      href="{% url 'home' %}">{% trans 'Main' %}</a>
                            </li>
                            <li class="nav__item nav__item_inline"><a class="breadcumbs__link nav__link nav__link_dark"
                                                                      href="{% url 'collection' collects.pk %}">{{ collects.title }}</a>
                            </li>
                            {% if categs %}
                                <li class="nav__item nav__item_inline">{{ categs.title }}</li>{% endif %}
                            {% if sales %}
                                <li class="nav__item nav__item_inline">{% trans 'Sales' %}</li>{% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>


    <!-- MAIN CONTENT-->
    <main class="main">

        <section class="section catalog">
            <div class="container">


                <nav class="nav align-right">
                    <ul class="nav__list">
                        {% for category in categories %}
                            {% if collects.pk == lions_heart.pk and category.lions_heart_present == False %}
                            {% elif collects.pk == revived.pk and category.revived_present == False %}
                            {% else %}
                                <li class="nav__item nav__item_inline">
                                    <!--IF CATEGORY IS ACTIVE SET CATALOG__MENU_ACTIVE-->{% autoescape off %}
                                    {% get_category 'collection_category' request collects.pk category.pk %}{% endautoescape %}{{ category.title }}</a>
                                </li>
                            {% endif %}

                        {% endfor %}

                    </ul>
                </nav>

                <div class="row">
                    <div class="col-md-3 align-center">
                        <div class="catalog__main"><span>
                  <div class="section__subtitle section__subtitle_theme">{% if collects.pk == revived.pk %}
                      {% trans "Women's" %}
                  {% else %}{% trans "Men's" %}{% endif %}<br>{% trans 'Collection' %}<br>
                  </div><img src="{{ collects.logo_image.url }}">
                  <p class="section__text section__text_neutral mt-30">{{ collects.description|linebreaksbr }}</p></span>
                        </div>
                    </div>

                    {% for item in object_list %}

                        <div class="col-md-3 align-center">
                            <div class="product"><span class="product__animation"></span><a class="product__link"
                                                                                            href="{% url 'item' item.pk %}">
                                {% if item.sales %}
                                    <span class="onsale"
                                          style="background: url({% static 'lions_heart_products/img/sale.png' %}) no-repeat;"></span>
                                {% endif %}
                                {% if item.best_seller %}
                                    <span class="onsale"
                                          style="background: url({% static 'lions_heart_products/img/best_seller.png' %}) no-repeat;"></span>
                                {% endif %}
                                <img class="product__img" src="{{ item.title_image.url }}"></a>
                                <div class="product__wrap"><a class="section__text section__text_dark"
                                                              href="{% url 'item' item.pk %}">{{ item.title }}</a>
                                    {% if item.get_first_attribute.sales_price %}
                                        <p class="section__text section__text_dark">{{ item.get_first_attribute.sales_price|convert }}<span> {% trans 'UAH' %}</span>
                                        </p>
                                    {% else %}
                                        <p class="section__text section__text_dark">{{ item.get_first_attribute.price|convert }}<span> {% trans 'UAH' %}</span>
                                        </p>
                                    {% endif %}

                                    <button data-href="{% url 'add_to_cart' item.pk %}"
                                            class="button button_uppercase product__button cart__catalogue">{% trans 'Add to cart' %}</button>

                                </div>

                            </div>
                        </div>

                    {% endfor %}

                </div>

                {% include 'lions_heart_products/pagination.html' %}
                {% include 'lions_heart_products/pagination_form.html' %}
        </section>
    </main>


{% endblock content %}

lions_heart_products/templates/lions_heart_products/delivery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

lions_heart_products/templates/lions_heart_products/index.html
{% load static from staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>

      <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5NPBW4N');</script>
<!-- End Google Tag Manager -->

      <script type="text/javascript">

function stopRKey(evt) {
  var evt = (evt) ? evt : ((event) ? event : null);
  var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null);
  if ((evt.keyCode == 13) && (node.type=="number"))  {return false;}
}

document.onkeypress = stopRKey;

</script>

  </head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="shortcut icon" href="{% static "lions_heart_products/img/favicon.ico" %}" type="image/x-icon">
  <title>Lion's Heart</title>
  <link href="{% static "lions_heart_products/css/libs.min.css" %}" rel="stylesheet">
  <link href="{% static "lions_heart_products/css/main.css" %}" rel="stylesheet">
  <link rel='stylesheet' href='https://apimgmtstorelinmtekiynqw.blob.core.windows.net/content/MediaLibrary/Widget/Map/styles/map.css' />
  <style>
    #myForm {
      display:inline;
    }
    @media (max-width: 768px) {
      #myForm {
        text-align: center;
      }
    }
  </style>
  <body>

  <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5NPBW4N"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

    <div class="wrapper">
    <!-- HEADER-->
    <header class="header">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
              <!-- LOGO--><a class="header__logo" href="{% url 'home' %}">
              <span><img src="{% static "lions_heart_products/img/logo.jpg" %}" alt="logo">
                  <img class="header__line" src="{% static "lions_heart_products/img/header-line.jpg" %}"></span></a>
          </div>
          <div class="col-md-9 col-xs-12 col-sm-12">

          {% load i18n %}


            <a class="header__mobile" href="#"><span class="header__hamburger"></span>
                <span class="header__hamburger"></span><span class="header__hamburger"></span></a>
            <!-- NAVIGATION-->
            <nav class="nav header__nav">
                <div class="header__additional">

            <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}">
    <select name="language" onchange="this.form.submit()">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                 {{ language.code }}
            </option>
        {% endfor %}
    </select>
    <div class="header__rate">$ {{ rate }}</div>
</form>
        </div>

              <ul class="nav__list nav__list_header">

                  <li class="nav__item nav__item_inline nav__item_has-child header__item"><span class="nav__link nav__link_dark nav__link_uppercase header__link header__link_has-child">{% trans 'Our collections' %}</span>
                   <!-- DROP-DOWN-->
                   <ul class="nav__list nav__list-child align-center">
                       <li class="nav__item header__item"><a class="nav__link nav__link_uppercase nav__link_dark header__link header__link_child" href="{% url 'collection' lions_heart.pk %}">{% trans "Men's" %}<br>{{ lions_heart }}</a>
                         <a class="nav__link nav__link_uppercase nav__link_dark header__link header__link_child" href="{% url 'collection' revived.pk %}">{% trans "Women's" %}<br>{{ revived }}</a></li>
                   </ul>
                    </li>
                <li class="nav__item nav__item_inline header__item"><a class="nav__link nav__link_uppercase nav__link_dark header__link" href="{% url 'about' %}">{% trans 'About' %}</a></li>
                <li class="nav__item nav__item_inline header__item"><a class="nav__link nav__link_uppercase nav__link_dark header__link" href="{% url 'blog' %}">{% trans 'Blog' %}</a></li>
                <li class="nav__item nav__item_inline header__item"><a class="nav__link nav__link_uppercase nav__link_dark header__link" href="{% url 'contacts' %}">{% trans 'Contacts' %}</a></li>
                <li class="nav__item nav__item_inline header__item"><a class="nav__link nav__link_uppercase nav__link_dark header__link" href="{% url 'sales' %}">{% trans 'Sales' %}</a></li>
                <li class="nav__item nav__item_inline header__item"><a class="nav__link nav__link_uppercase nav__link_dark header__link" href="{% url 'reviews' %}">{% trans 'Acknowledgments' %}</a></li>
{#                <li class="nav__item nav__item_inline header__item"><a class="nav__link nav__link_uppercase nav__link_dark header__link" href="{% url 'reviews' %}">{% trans 'Delivery&Payment' %}</a></li>#}
                <li class="nav__item nav__item_inline header__item"><a id="cart" class="nav__link nav__link_uppercase nav__link_dark header__link" href="{% url 'cart' %}">{% trans 'Cart' %}
                    <span id="cart_items" class="cart__length" >{{ items }}</span></a></li>
              </ul>

            </nav>
          </div>
        </div>
      </div>

    </header>
    {% block content %}
    <!-- MAIN CONTENT-->
    <main class="main">
      <section class="home">
        <div class="home__slider">
                  <div class="swiper-container">
                    <div class="swiper-wrapper">

                        {% for banner in company_info.banners_set.all %}
                        <div class="swiper-slide" style="background-image:url({{ banner.image.url }});">
                      <div class="home__dark">
                          <div class="home__title">{{ company_info.banner_title }}</div>
                          <a class="home__button" {% if banner.is_revived %}
                             href="{% url 'collection' revived.pk %}"
                             {% else %}
                             href="{% url 'collection' lions_heart.pk %}"
                             {% endif %}>
                              {% trans 'start shopping' %}<span class="home__button-inner"></span></a>
                        </div>
                      </div>
                        {% endfor %}

                    </div>
                    <div class="swiper-pagination"></div>
                  </div>
                </div>
      </section>
    </main>
    {% endblock content %}
    <footer class="footer">
      <div class="container">
        <div class="row">


              <div class="col-md-2 col-sm-3">
            <!-- FIRST MENU-->
            <nav class="nav nav_footer">
              <ul class="nav__list">
                   {% for category in categories_first %}
                {% if category.lions_heart_present %}<li class="nav__item footer__item"><a class="nav__link nav__link_light nav__link_uppercase footer__link" href="{% url 'collection_category' lions_heart.pk category.pk  %}">{{ category.title }}</a></li>{% endif %}
                   {% endfor %}
              </ul>
            </nav>
          </div>


         <div class="col-md-2 col-sm-3">
            <!-- FIRST MENU-->
            <nav class="nav nav_footer">
              <ul class="nav__list">
                   {% for category in categories_second %}
                {% if category.lions_heart_present %}<li class="nav__item footer__item"><a class="nav__link nav__link_light nav__link_uppercase footer__link" href="{% url 'collection_category' lions_heart.pk category.pk  %}">{{ category.title }}</a></li>{% endif %}
                   {% endfor %}
              <li class="nav__item footer__item"><a class="nav__link nav__link_light nav__link_uppercase footer__link" href="{% url 'sales' %}">{% trans 'Sales' %}</a></li>
              </ul>
            </nav>
          </div>


            <div class="col-md-2">
            <!-- SECOND MENU-->
            <nav class="nav nav_footer">
              <ul class="nav__list">
                <li class="nav__item footer__item"><a class="nav__link nav__link_light nav__link_capitalize footer__link" href="{% url 'about' %}">{% trans 'About' %}</a></li>
                <li class="nav__item footer__item"><a class="nav__link nav__link_light nav__link_capitalize footer__link" href="{% url 'blog' %}">{% trans 'Blog' %}</a></li>
                <li class="nav__item footer__item"><a class="nav__link nav__link_light nav__link_capitalize footer__link" href="{% url 'contacts' %}">{% trans 'Contacts' %}</a></li>
              </ul>
            </nav>
          </div>

          <div class="col-md-3 col-md-offset-3 align-right">
            <!--TELL-->
            <p class="footer__subtitle mt-20">{% trans 'Call' %}</p><a class="footer__tel" href="tel:{{ company_info.phone_set.all.0.phone }}">{{ company_info.phone_set.all.0.phone }}</a>
               <div class="footer__social social-footer">
                   <a class="social-footer__inner" href="https://www.instagram.com/_lions.heart_/?hl=ru" target="_blank"><img src="{% static "lions_heart_products/img/instagram.png" %}" alt="facebook"></a>
                   <a class="social-footer__inner" href="https://www.facebook.com/LionsHeartJewellery/" target="_blank"><img src="{% static "lions_heart_products/img/facebook.png" %}" alt="facebook"></a>
               </div>
          </div>
        </div>

      <div class="row">
           <div class="col-md-12"><a class="footer__copyright" href="https://gofriends.pro/ru/">All rights reserved GoFriends &copy; 2018</a></div>
         </div>

      </div>
    </footer>
    </div>


    <script src="{% static "lions_heart_products/js/libs.min.js" %}"></script>
    <script src="{% static "lions_heart_products/js/main.js" %}"></script>
  </body>
</html>