Lions_Heart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [

    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^', include('lions_heart_products.urls')),
    url(r'^', include('lions_heart_blog.urls')),
    url(r'^', include('lions_heart_cart.urls')),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(url(r'^', include('lions_heart_products.urls')))
urlpatterns += i18n_patterns(url(r'^', include('lions_heart_blog.urls')))
urlpatterns += i18n_patterns(url(r'^', include('lions_heart_cart.urls')))

if settings.DEBUG:
        import debug_toolbar
        urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls))] + urlpatterns

lions_heart_blog/urls.py
from django.conf.urls import url, include
from .views import PostListView, PostDetailView, CommentCreate, AboutView, ContactView, ReviewsListView, ReviewCreate


urlpatterns = [
    url(r'^blog/$', PostListView.as_view(), name='blog'),
    url(r'^blog_posts/(?P<pk>\d+)/$', PostDetailView.as_view(), name='blog_detail'),
    url(r'^blog_posts/(?P<post_id>\d+)/new_comment/$', CommentCreate.as_view(), name='new_comment'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^contacts/$', ContactView.as_view(), name='contacts'),
    url(r'^reviews/$', ReviewsListView.as_view(), name='reviews'),
    url(r'^review_create/$', ReviewCreate.as_view(), name='review_create'),

    url(r'^reviews/captcha/', include('captcha.urls')),
]

lions_heart_blog/models.py
from django.db import models
from lions_heart_products.models import CommonInfo
from django.utils.translation import ugettext_lazy as _


class Post(CommonInfo):

    class Meta(CommonInfo.Meta):
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")

    title = models.CharField(max_length=256, verbose_name=_('name'))
    body_text = models.TextField(blank=True, null=True, verbose_name=_('text'))
    main_image = models.ImageField(blank=True, null=True, upload_to='blog/pictures',
                                   verbose_name=_('main image'))

    def __str__(self):
        return "{}".format(self.title)


class Comment(CommonInfo):

    class Meta(CommonInfo.Meta):
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

    author = models.CharField(max_length=256, blank=True, null=True, verbose_name=_('author'))
    comment = models.TextField(blank=True, null=True, verbose_name=_('comment'))
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name=_('post'))

    def __str__(self):
        return "{}-{}".format(self.post, self.created)


class Image(models.Model):

    class Meta(object):
        verbose_name = _("Image")
        verbose_name_plural = _("Images")

    image = models.ImageField(upload_to='blog/pictures', verbose_name=_('image'))
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name=_('post'))

    def __str__(self):
        return "{}-{}".format(self.image, self.post)


class CompanyInformation(models.Model):

    class Meta(object):
        verbose_name = _("Company")
        verbose_name_plural = _("Company")

    about = models.TextField(verbose_name=_('about'))
    about_title_image = models.ImageField(blank=True,
                                          null=True,
                                          upload_to='company/pictures',
                                          verbose_name=_('about_image'))
    banner_title = models.CharField(max_length=256, blank=True, null=True)


class Phone(models.Model):
    phone = models.CharField(max_length=256)
    company = models.ForeignKey(CompanyInformation, on_delete=models.CASCADE)


class Email(models.Model):
    mail = models.EmailField()
    company = models.ForeignKey(CompanyInformation, on_delete=models.CASCADE)


class Address(models.Model):
    address = models.CharField(max_length=256)
    company = models.ForeignKey(CompanyInformation, on_delete=models.CASCADE)


class CompanyImage(models.Model):

    class Meta(object):
        verbose_name = _("Diploma")
        verbose_name_plural = _("Diplomas")

    image = models.ImageField(upload_to='company/pictures', verbose_name=_('image'))
    company = models.ForeignKey(CompanyInformation, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.image)


class Banners(models.Model):

    class Meta(object):
        verbose_name = _("Banner")
        verbose_name_plural = _("Banners")

    image = models.ImageField(upload_to='company/pictures', verbose_name='banner')
    company = models.ForeignKey(CompanyInformation, on_delete=models.CASCADE)
    is_revived = models.BooleanField(default=False)

    def __str__(self):
        return "{}".format(self.image)


class Reviews(CommonInfo):

    class Meta(CommonInfo.Meta):
        verbose_name = _("Review")
        verbose_name_plural = _("Reviews")

    author = models.CharField(max_length=35, verbose_name=_('name'))
    review = models.TextField(max_length=1332, verbose_name=_('review'))

    def __str__(self):
        return "{}-{}".format(self.created, self.author)

lions_heart_blog/forms.py
from django.forms import ModelForm
from .models import Comment, Reviews
from captcha.fields import CaptchaField


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ['author', 'comment']


class ReviewForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Reviews
        fields = '__all__'

lions_heart_blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import ListView, DetailView, TemplateView
from .models import Post, Comment, CompanyInformation, Reviews
from django.views.generic.edit import CreateView
from django.urls import reverse
from .forms import CommentForm, ReviewForm
from django.contrib import messages
from django.utils.translation import ugettext as _
from django.utils.dateformat import DateFormat
from django.http import JsonResponse
from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url


class PostListView(ListView):
    model = Post
    template_name = 'lions_heart_blog/blog.html'
    paginate_by = 8


class PostDetailView(DetailView):
    model = Post
    template_name = 'lions_heart_blog/blog_detail.html'

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context


class CommentCreate(CreateView):

    model = Comment
    form_class = CommentForm
    template_name = 'lions_heart_blog/blog_detail.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.post = Post.objects.get(pk=self.kwargs['post_id'])
        obj.save()
        return HttpResponseRedirect(reverse('blog_detail', args=(self.kwargs['post_id'])))

    def get_success_url(self):
            return reverse('blog_detail', args=(self.kwargs['post_id']))


class AboutView(ListView):
    template_name = 'lions_heart_blog/about.html'
    model = CompanyInformation


class ContactView(ListView):
    template_name = 'lions_heart_blog/contacts.html'
    model = CompanyInformation


class ReviewsListView(ListView):
    model = Reviews
    template_name = 'lions_heart_blog/reviews.html'

    def get_context_data(self, **kwargs):
        context = super(ReviewsListView, self).get_context_data(**kwargs)
        context['form'] = ReviewForm
        return context


class ReviewCreate(CreateView):

    model = Reviews
    form_class = ReviewForm

    def form_valid(self, form):
        response_data = {'error': ''}
        obj = form.save(commit=False)
        obj.save()
        response_data['name'] = obj.author
        response_data['review'] = obj.review
        response_data['created'] = DateFormat(obj.created).format('d-m-Y')
        response_data['key'] = CaptchaStore.generate_key()
        response_data['image_url'] = captcha_image_url(response_data['key'])
        return JsonResponse(response_data)

    def form_invalid(self, form):
        response_data = {'name': '', 'review': '', 'created': ''}
        response_data['key'] = CaptchaStore.generate_key()
        response_data['image_url'] = captcha_image_url(response_data['key'])
        response_data['error'] = _('Error. Please, try again.')
        return JsonResponse(response_data)

lions_heart_blog/templates/lions_heart_blog/about.html
{% extends 'lions_heart_products/index.html' %}
{% load i18n %}

{% block content %}


    <!-- MAIN CONTENT-->
    <main class="main">
        <section class="section about">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="section__title section__title_dark about__title">{% trans 'About' %}</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="about__img" style="background-image:url(
                                {{ MEDIA_URL }}{{ object_list.first.about_title_image.url }});"></div>

                    </div>
                    <div class="col-md-6">
                        <p class="section__text section__text_neutral section__text_mb-0" style="text-align: justify">
                            {{ object_list.first.about|linebreaksbr }}
                        </p>

                    </div>
                </div>

                <!-- Diploma-->
                <div class="row mt-20 mb-20">

                    {% for image in object_list.first.companyimage_set.all %}

                        <div class="col-md-3">
                            <div class="about__single single-about"><img class="single-about__img"
                                                                         src="{{ image.image.url }}"></div>
                        </div>

                    {% endfor %}

                </div>
            </div>

        </section>
    </main>


{% endblock content %}

lions_heart_blog/templates/lions_heart_blog/blog.html
{% extends 'lions_heart_products/index.html' %}
{% load i18n %}

{% block content %}


    <!-- MAIN CONTENT-->
    <main class="main">
        <section class="section blog">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="section__title section__title_dark about__title">{% trans 'Blog' %}</h2>
                    </div>
                </div>

                {% for post in object_list %}

                    <div class="row mt-10">
                    <div class="col-md-12 col-sm-12">
                        <!-- SINGLE BLOG-->
                        <div class="blog__text"><a class="blog__box" href="{% url 'blog_detail' post.pk %}">
                            {% if post.main_image %}
                                <div class="blog__img" style="background-image:url({{ post.main_image.url }});"></div>
                                </a>
                            {% endif %}
                            <p>{{ post.title }}</p>
                            <p style="text-align: justify">{{ post.body_text|truncatechars:500 }}</p>
                        </div>
                        <div class="blog__bottom bottom-blog">
                            <div class="bottom-blog__date">{{ post.created|date:'d-m-Y' }}</div>
                            <a class="bottom-blog-more"
                               href="{% url 'blog_detail' post.pk %}">{% trans 'read more' %}</a>
                        </div>
                    </div>

                {% endfor %}

                {% include 'lions_heart_products/pagination.html' %}

                </div>

            </div>

        </section>
    </main>

{% endblock content %}

lions_heart_blog/templates/lions_heart_blog/blog_detail.html
{% extends 'lions_heart_products/index.html' %}
{% load i18n %}

{% block content %}

    <!-- MAIN CONTENT-->
    <main class="main">
        <section class="section blog">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 align-center">
                        <h2 class="section__title section__title_dark about__title">{{ post.title }}</h2>
                        <p class="blog__single-date">{{ post.created|date:'d-m-Y' }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10 col-md-offset-1 align-center" style="margin-bottom: 20px"><img
                            src={{ post.main_image.url }}></div>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <p class="section__text section__text_neutral"
                           style="text-align: justify">{{ post.body_text }}</p>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

lions_heart_blog/templates/lions_heart_blog/contacts.html
{% extends 'lions_heart_products/index.html' %}
{% load i18n %}
{% load static from staticfiles %}

{% block content %}


    <!-- MAIN CONTENT-->
    <main class="main">
      <section class="section contacts">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <h2 class="section__title section__title_dark contacts__title">{% trans 'Contacts' %}</h2>
              <div class="contacts__wrap">

                <div class="contacts__box">
                {% for phone in companyinformation_list.first.phone_set.all %}

              <a class="contacts__text contacts__text_link contacts__tel" href="tel:{{ phone.phone }}"><img class="contacts__img" src={% static "lions_heart_products/img/tel.png" %} alt="telephone">{{ phone.phone }}</a>

                  {% endfor %}
                  </div>

                  <div class="contacts__box">
                  {% for mail in companyinformation_list.first.email_set.all %}

                  <a class="contacts__text contacts__text_link" href="mailto: {{ mail.mail }}"><img class="contacts__img" src={% static "lions_heart_products/img/mail.png" %}>{{ mail.mail }}</a>

                  {% endfor %}
                  </div>

                  <div class="contacts__box">
                  {% for address in companyinformation_list.first.address_set.all %}

                <p class="contacts__text"><img class="contacts__img" src={% static "lions_heart_products/img/place.png" %}>{{ address.address }}</p>

                  {% endfor %}
                  </div>

              </div>
            </div>
          </div>
        </div>
      </section>
      <div id="map"></div>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC1q759LlOAGNKLwmPhz4ktyEo-MWe5Z6U&amp;callback=initMap"></script>
      <script>
         // When the window has finished loading create our google map below
        google.maps.event.addDomListener(window, 'load', init);

        function init() {
            // Basic options for a simple Google Map
            // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
            var mapOptions = {
                // How zoomed in you want the map to start at (always required)
                zoom: 15,

                // The latitude and longitude to center the map (always required)
                center: new google.maps.LatLng(50.507823,30.498389),

                // How you would like to style the map.
                // This is where you would paste any style found on Snazzy Maps.
                styles: [{"featureType":"all","elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#000000"},{"lightness":40}]},{"featureType":"all","elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#000000"},{"lightness":16}]},{"featureType":"all","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":17},{"weight":1.2}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":21}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":16}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":19}]},{"featureType":"water","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":17}]}]
            };

            // Get the HTML DOM element that will contain your map
            // We are using a div with id="map" seen below in the <body>
            var mapElement = document.getElementById('map');

            // Create the Google Map using our element and options defined above
            var map = new google.maps.Map(mapElement, mapOptions);

            // Let's also add a marker while we're at it
            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(50.507823,30.498389),
                map: map,
                title: 'Dream Town'
            });
        }
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC1q759LlOAGNKLwmPhz4ktyEo-MWe5Z6U&amp;callback=initMap"></script>
    </main>

{% endblock content %}

lions_heart_blog/templates/lions_heart_blog/reviews.html
{% extends 'lions_heart_products/index.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}


<!-- MAIN CONTENT-->
    <main class="main">
      <section class="section blog">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <h2 class="section__title section__title_dark about__title">{% trans 'Acknowledgments' %}</h2>
            </div>
          </div>

            <p id="error" style="color: red"></p>

        <h4>{% trans 'Please, leave your message:' %}</h4>

            <div style="margin-bottom: 20px">
                <form id="review_form" method="post" action="{% url 'review_create' %}">
                  {% csrf_token %}

                    {% trans 'Name:' %}
                    <p>{% render_field form.author %}</p>
                    {% trans 'Message:' %}
                    <p>{% render_field form.review style='width:450px' %}</p>
                    <p>{% render_field form.captcha %}</p>

                <input type="submit" value="{% trans 'Leave message' %}" class="button button_uppercase product__button">
                </form>
            </div>
            <hr>
            <div id="review">
                <p id="author_date"></p>
                <p id="review_text" class="blog__text" style="text-align: justify"></p>
                {% for review in object_list %}
                <p>{{ review.author }} {{ review.created|date:'d-m-Y' }}</p>
                    <p class="blog__text" style="text-align: justify">{{ review.review }}</p><hr>
                {% endfor %}
            </div>

        </div>
      </section>
    </main>

{% endblock content %}